"use client";
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Title from "./components/Title";
import SearchInput from "./components/SearchInput";
import Btn from "./components/Btn";
import { useEffect, useState } from "react";

export default function Home() {
  const [random, setRandom] = useState(1);
  useEffect(() => setRandom(Math.floor(Math.random() * 1025)), []);

  return (
    <>
      <Head>
        <title>Another Pokedex APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main style={{ backgroundColor: "white" }} className="container center">
        <Title />
        <br />
        <h1>Serach Pokemon</h1>
        <div>
          <Image
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg"
            alt="shiny pikachu"
            width={300}
            height={300}
          />
          <SearchInput />
          <div className="center">
            <div className="row">
              <Btn goTo={`/pokemons/info/${random}`} text="Random Pokemon" />
              <Btn goTo={`/pokemons/`} text="List random Pokemons" />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
